### ISSUE TITLE
暂时看不到您的京东赚赚好友助力码

### ISSUE THREAD

**Issue by eromoe** [LXK9301/jd_scripts#123]
无法看到 京东赚赚的助力码

```
由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

开始
随机取20个码放到您固定的互助码后面(不影响已有固定互助)
第1个京东账号将要助力的好友["ATGEC3-fsrn13aiaEqiM","AUWE5maSSnzFeDmH4iH0elA","AUWE5m6WUmDdZC2mr1XhJlQ","AUWE5m_jEzjJZDTKr3nwfkg","A06fNSRc4GIqY38pMBeLKQE2InZA","AUWE5mf7ExDZdDmH7j3wfkA","AUWE5m6jBy2cNAWX7j31Pxw","AUWE5mK2UnDddDTX61S1Mkw","AUWE5mavGyGZdWzP5iCoZwQ","AUWE5m6-VzWRZCjL8jH1Ilg","AQmQLyunFyjIP","AUWE55sjFs0JKchSBuRsW","S5LUxEVc","S7aUiHkpboA","Sv_V0RRYa81XTJR-b1A","S5KkcRkpPpFfVIB2ilPQLIA","S5KkcRxwb9weGJhr2k_EPJQ","S5KkcRUpIpwCDc0_ynP5bJw","957220c1422a44f29c4d725ca9db30f9","SxawqCUNAtg","Q5gUHzoqd7A_dw2mVDXMFw==","AUWE5mPyWxWMPW2Gt3XVNwQ","S5KkcPVZekQaefE2M5q58","S5KkcHn57lwiIYWCnwrZy","S16wtFx8Y8FDTIRL2kfU","A3Y33ShIKGo2J3-tOCvf8","S-qwtB0MY91fTJRw","Sv_h7RBYQ8VHTIgfwlv8PdAY","S5KkcRxcY8AXTIB_wlvMMcQ"]

❗️京东赚赚, 错误!
TypeError: Cannot read property 'canStartNewAssist' of undefined
    at /mithril/jd-base/scripts/jd_jdzz.js:202:28
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/mithril/jd-base/scripts/jd_jdzz.js:519:4869)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
好友任务已完成，下次再给他助力吧~
已满5人助力,暂时看不到您的京东赚赚好友助力码
去做任务：关注德青源赢好礼
任务失败，错误信息：啊哦，活动太火爆～~
去做任务：逛逛爆款礼盒
任务失败，错误信息：啊哦，活动太火爆～~

==============📣系统通知📣==============

```

**Comment by LXK9301** [comment]
已满5人助力,暂时看不到您的京东赚赚好友助力码

**Comment by LXK9301** [comment]
还有这活动互助。目前已经下线
