### ISSUE TITLE
口袋书店 API请求失败，请检查网路重试

### ISSUE THREAD

**Issue by qxy0789** [LXK9301/jd_scripts#191]
==============📣系统通知📣==============

口袋书店

不要在BoxJS手动复制粘贴修改cookie

2021-01-22T04:05:10.289Z 4c64dd79-264b-4074-b671-8b611c9dfdb6 Response code 493 (undefined),undefined

2021-01-22T04:05:10.289Z 4c64dd79-264b-4074-b671-8b611c9dfdb6 口袋书店 API请求失败，请检查网路重试

2021-01-22T04:05:10.937Z 4c64dd79-264b-4074-b671-8b611c9dfdb6 SyntaxError: Unexpected token < in JSON at position 0

    at JSON.parse (<anonymous>)

    at jsonParse (/var/user/jd_bookshop.js:735:19)

    at /var/user/jd_bookshop.js:378:33

    at /var/user/jd_bookshop.js:744:5858

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

2021-01-22T04:05:10.937Z 4c64dd79-264b-4074-b671-8b611c9dfdb6

==============📣系统通知📣==============

口袋书店

不要在BoxJS手动复制粘贴修改cookie

2021-01-22T04:05:10.937Z 4c64dd79-264b-4074-b671-8b611c9dfdb6 Response code 493 (undefined),undefined

2021-01-22T04:05:10.937Z 4c64dd79-264b-4074-b671-8b611c9dfdb6 口袋书店 API请求失败，请检查网路重试

2021-01-22T04:05:11.587Z 4c64dd79-264b-4074-b671-8b611c9dfdb6 SyntaxError: Unexpected token < in JSON at position 0

    at JSON.parse (<anonymous>)

    at jsonParse (/var/user/jd_bookshop.js:735:19)

    at /var/user/jd_bookshop.js:378:33

    at /var/user/jd_bookshop.js:744:5858

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

2021-01-22T04:05:11.587Z 4c64dd79-264b-4074-b671-8b611c9dfdb6

**Comment by qxy0789** [comment]
云函数部署的

**Comment by LXK9301** [comment]
再次运行尝试看
