### ISSUE TITLE
京喜农场token无法解析的问题

### ISSUE THREAD

**Issue by iOSleep** [LXK9301/jd_scripts#212]
运行环境：docker1

yml里面填写的内容类似
```yml
 - JXNCTOKENS='{"farm_jstoken":"ad780b38f30b8458b9837c526a63fca4","timestamp":"1611338367786","phoneid":"d39c32ecff1e1f1502492298a2f70076b9b64048"}'&'{"farm_jstoken":"08864bac534f65e526b4c46dd6831e9d","timestamp":"1611340561667","phoneid":"21b6f94c68e67bc3e8ad49af224c142a1b9bb253"}'       
```

docker 环境变量大概这个样子
```json
"JXNCTOKENS='{\"farm_jstoken\":\"ad780b38f30b8458b9837c526a63fca4\",\"timestamp\":\"1611338367786\",\"phoneid\":\"d39c32ecff1e1f1502492298a2f70076b9b64048\"}'&'{\"farm_jstoken\":\"08864bac534f65e526b4c46dd6831e9d\",\"timestamp\":\"1611340561667\",\"phoneid\":\"21b6f94c68e67bc3e8ad49af224c142a1b9bb253\"}'",
            
```

错误截图

```js

您的京喜农场 token 选择的是用&隔开

共2个京东账号

(node:106) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at /scripts/jd_jxnc.js:146:56
    at Array.forEach (<anonymous>)
    at /scripts/jd_jxnc.js:145:38
    at new Promise (<anonymous>)
    at requireConfig (/scripts/jd_jxnc.js:122:12)
    at /scripts/jd_jxnc.js:66:11
    at Object.<anonymous> (/scripts/jd_jxnc.js:100:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:106) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

参考地址:  https://github.com/LXK9301/jd_scripts/blob/master/githubAction.m

**Comment by iOSleep** [comment]
行吧，看了下pr的share的代码，貌似把引号去了就好了，希望可以改下文档。。。
