### ISSUE TITLE
神仙书院答题出现报错Cookie not in this host's domain

### ISSUE THREAD

**Issue by chxmtl2** [LXK9301/jd_scripts#273]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [ ] Docker2 
- [x] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：神仙书院答题出错，报错日志Cookie not in this host's domain

### (2) 详细日志
A：当前用户金币5025
答题开启成功
去查询第1题：【哪一个不是联合利华工厂所在地？】
去搜索哪一个不是联合利华工厂所在地？沈阳		

❗️京东神仙书院答题, 错误!
Error: Cookie not in this host's domain. Cookie:bing.com Request:null
    at CookieJar.setCookie (/home/ipi/jd/scripts/node_modules/tough-cookie/lib/cookie.js:1133:15)
    at CookieJar.setCookie (/home/ipi/jd/scripts/node_modules/universalify/index.js:5:67)
    at CookieJar.setCookieSync (/home/ipi/jd/scripts/node_modules/tough-cookie/lib/cookie.js:1642:21)
    at EventEmitter.isSurge.isLoon.isQuanX.isNode.got.on (/home/ipi/jd/scripts/jd_immortal_answer.js:396:4735)
    at EventEmitter.emit (events.js:198:13)
    at Request.fns.(anonymous function).args (/home/ipi/jd/scripts/node_modules/got/dist/source/core/utils/proxy-events.js:7:16)
    at Request.emit (events.js:198:13)
    at Request._onResponseBase (/home/ipi/jd/scripts/node_modules/got/dist/source/core/index.js:886:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property '1' of null
    at $.get (/home/ipi/jd/scripts/jd_immortal_answer.js:283:70)
    at isSurge.isLoon.isQuanX.isNode.got.on.then.t (/home/ipi/jd/scripts/jd_immortal_answer.js:396:4869)
    at process._tickCallback (internal/process/next_tick.js:68:7)
去搜索哪一个不是联合利华工厂所在地？金山

❗️京东神仙书院答题, 错误!

### (1) Node.js版本

A：v10.21.0

### (2) npm版本

A：6.14.4

### (3)npm install的日志

A：audited 206 packages in 5.247s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by HUGHHUXIAOJUN** [comment]
为啥我没看到答题的脚本，js我到是看到别人发的

**Comment by Yvan0329** [comment]
一样的问题

**Comment by HUGHHUXIAOJUN** [comment]
我之前没注意日志。。运行了下 一样的问题，他们说这个脚本用qx 成功了，我node试了没成功 https://raw.githubusercontent.com/i-chenzhe/qx/main/jd_dati.js
