### ISSUE TITLE
年兽报错

### ISSUE THREAD

**Issue by Volatile0** [LXK9301/jd_scripts#42]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
运行过程中报错
### (2) 详细日志
A：

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at eval (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:342:27)
    at got.post.then.message (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:634:5694)
❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at eval (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:471:32)
    at got.post.then.message (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:634:5694)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
忽略即可，不影响使用
