### ISSUE TITLE
宠汪汪偷好友积分与狗粮, 错误!

### ISSUE THREAD

**Issue by google-mirror** [LXK9301/jd_scripts#43]
❗️宠汪汪偷好友积分与狗粮, 错误!
TypeError: Cannot read property 'stealFood' of null
    at C:\Users\Administrator\Desktop\jd_scripts\jd_joy_steal.js:324:43
    at C:\Users\Administrator\Desktop\jd_scripts\jd_joy_steal.js:579:4546
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️宠汪汪偷好友积分与狗粮, 错误!
TypeError: Cannot destructure property 'friendHomeCoin' of 'enterFriendRoomRes.data' as it is null.
    at stealFriendCoin (C:\Users\Administrator\Desktop\jd_scripts\jd_joy_steal.js:295:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async stealFriendCoinFun (C:\Users\Administrator\Desktop\jd_scripts\jd_joy_steal.js:205:9)
    at async jdJoySteal (C:\Users\Administrator\Desktop\jd_scripts\jd_joy_steal.js:122:11)
    at async C:\Users\Administrator\Desktop\jd_scripts\jd_joy_steal.js:88:7

**Comment by LXK9301** [comment]
时不时出现这个问题吧， 解决办法就只能加强脚本判断了，你再次运行可能又正常了
