### ISSUE TITLE
使用docker炸年兽时报错

### ISSUE THREAD

**Issue by chanho0** [LXK9301/jd_scripts#56]
使用方式：jd-base（docker），具体：https://github.com/EvineDeng/jd-base，已更到手动最新版
报错内容
❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /jd/scripts/jd_nian.js:562:46
    at got.post.then.message (/jd/scripts/jd_nian.js:949:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
去做宝洁店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /jd/scripts/jd_nian.js:562:46
    at got.post.then.message (/jd/scripts/jd_nian.js:949:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
去做蒙牛店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /jd/scripts/jd_nian.js:562:46
    at got.post.then.message (/jd/scripts/jd_nian.js:949:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
去做欧莱雅店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /jd/scripts/jd_nian.js:562:46
    at got.post.then.message (/jd/scripts/jd_nian.js:949:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
去做伊利店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /jd/scripts/jd_nian.js:562:46
    at got.post.then.message (/jd/scripts/jd_nian.js:949:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❌ 京东炸年兽🧨, 失败! 原因: TypeError: $.taskVos is not iterable!

🔔京东炸年兽🧨, 结束! 🕛 16.371 秒

谢谢

**Comment by xiaokexiang** [comment]
看了下和docker没关系诶，这个docker版本是昨天就有的，这个错误是下午的新代码后出现的，感觉是升级的问题

**Comment by 4rat** [comment]
me too

**Comment by svnyang** [comment]
同上

**Comment by Michaol** [comment]
同一样的错

**Comment by hslzyd** [comment]
俺也一样
前面跑一次还正常的，之后再手动运行就不行了，应该是脚本判断出错超过一定次数退出了

**Comment by bowenspring** [comment]
一样问题，坐等脚本更新....

**Comment by tianya908** [comment]
同一样的错

**Comment by fengmikaelson** [comment]
是不是会自动助力别人。。。发现了莫名的助力

**Comment by laststory117** [comment]
可能是请求太频繁导致的
![image](https://user-images.githubusercontent.com/24773896/104916041-779e5e00-59cc-11eb-8464-0fca19f5decc.png)
去做店铺任务后面加个延时就好了
![image](https://user-images.githubusercontent.com/24773896/104916091-8f75e200-59cc-11eb-86a6-9895e04793ae.png)

**Comment by Tony-N2** [comment]
请问下怎么看年兽的代码？ 我输入互助码没看见

**Comment by bluewatercg** [comment]
`  for(let vo of data.data.viewLogo.list){
                console.log(`去做${vo.name}店铺任务`)
                await $.wait(2000)
                await shopLotteryInfo(vo.desc)
                await $.wait(2000)
              }`
还是提示
去做OLAY店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /mnt/udisk/lib/jd/scripts/jd_nian.js:567:46
    at got.post.then.message (/mnt/udisk/lib/jd/scripts/jd_nian.js:954:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by LXK9301** [comment]
@bluewatercg 更新脚本在跑一次试试看

**Comment by MisterGlasses** [comment]
最初的脚本执行是没有问题的 但是会漏任务

**Comment by Gino-Wong** [comment]
> @bluewatercg 更新脚本在跑一次试试看

更新完再跑没问题啦 ；）

**Comment by chanho0** [comment]
已修复，方法如下，感谢作者

> @bluewatercg 更新脚本在跑一次试试看
